data:
  data_dir: "./data"
  image_size: 500
  batch_size: 16

training:
  epochs: 30
  learning_rate: 0.0001
  seed: 1024
  resume: true
  resume_model: "densenet121"   # model to resume incase of error or shutdown
  resume_epoch: 29


models:
  - name: "densenet121"
    pretrained: true


mlflow:
  experiment_name: "CHD-CXR-Experiments"
  tracking_uri: "file:./experiments/mlruns"



