data:
  data_dir: "./data"
  image_size: 500
  batch_size: 16

training:
  epochs: 30
  learning_rate: 0.0001
  seed: 1024

models:
  - name: "resnet18"
    pretrained: true

  - name: "resnet50"
    pretrained: true

  - name: "densenet121"
    pretrained: true

mlflow:
  experiment_name: "CHD-CXR-Experiments"
  tracking_uri: "file:./experiments/mlruns"
