data:
  data_dir: "./data"
  image_size: 500
  batch_size: 16

training:
  epochs: 30
  learning_rate: 0.0001
  seed: 1024
  resume: true
  resume_model: "mobilenet_v2"   # model to resume incase of error or shutdown
  resume_epoch: 12


models:

  - name: "mobilenet_v2"
    pretrained: true

  - name: "squeezenet1_1"
    pretrained: true

mlflow:
  experiment_name: "CHD-CXR-Experiments"
  tracking_uri: "file:./experiments/mlruns"



